In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/cars-dataset/used_cars_data.csv

In [2]:
df=pd.read_csv('/kaggle/input/cars-dataset/used_cars_data.csv')

In [3]:
df.head(3)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50

In [4]:
filtre=df['Name'].str.contains("Civic")
df[filtre]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
114,114,Honda Civic 2006-2010 1.8 V MT,Delhi,2010,71088,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,3.35
139,139,Honda Civic 2006-2010 1.8 V MT,Delhi,2012,88578,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,3.95
447,447,Honda Civic 2006-2010 1.8 S AT,Pune,2008,61938,Petrol,Automatic,Second,12.9 kmpl,1799 CC,130 bhp,5.0,NaN,2.65
554,554,Honda Civic 2006-2010 1.8 S MT,Ahmedabad,2007,51000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,4.90
978,978,Honda Civic 2010-2013 1.8 V MT,Kolkata,2010,38000,Petrol,Manual,First,14.8 kmpl,1799 CC,130.2 bhp,5.0,NaN,2.00
1174,1174,Honda Civic 2006-2010 1.8 V MT,Delhi,2008,72000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,2.50
1201,1201,Honda Civic 2010-2013 1.8 S MT,Mumbai,2012,92000,Petrol,Manual,Second,14.8 kmpl,1799 CC,130.2 bhp,5.0,NaN,3.35
1278,1278,Honda Civic 2010-2013 1.8 S MT,Mumbai,2010,86000,Petrol,Manual,First,14.8 kmpl,1799 CC,130.2 bhp,5.0,NaN,2.90
1507,1507,Honda Civic 2006-2010 1.8 V AT,Hyderabad,2008,95000,Petrol,Automatic,Second,12.9 kmpl,1799 CC,130 bhp,5.0,NaN,3.00
1751,1751,Honda Civic 2006-2010 1.8 S MT,Chennai,2006,110000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,2.65
1952,1952,Honda Civic 2006-2010 1.8 V AT,Bangalore,2011,72000,Petrol,Automatic,Second,12.9 kmpl,1799 CC,130 bhp,5.0,NaN,5.50
2238,2238,Honda Civic 2006-2010 1.8 V MT,Hyderabad,2008,152000,Petrol,Manual,Second,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,3.00
2498,2498,Honda Civic 2010-2013 1.8 V MT,Pune,2010,61700,Petrol,Manual,First,14.8 kmpl,1799 CC,130.2 bhp,5.0,NaN,2.95
2590,2590,Honda Civic 2006-2010 1.8 (E) MT,Hyderabad,2007,77000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,2.50
2740,2740,Honda Civic 2006-2010 1.8 S MT,Ahmedabad,2009,89000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,4.25
2996,2996,Honda Civic 2006-2010 1.8 S AT,Pune,2007,93000,Petrol,Automatic,Second,12.9 kmpl,1799 CC,130 bhp,5.0,NaN,2.60
3179,3179,Honda Civic 2010-2013 1.8 S MT,Hyderabad,2011,55000,Petrol,Manual,First,14.8 kmpl,1799 CC,130.2 bhp,5.0,NaN,5.00
3249,3249,Honda Civic 2006-2010 1.8 V AT,Delhi,2011,62000,Petrol,Automatic,First,12.9 kmpl,1799 CC,130 bhp,5.0,NaN,3.75
3323,3323,Honda Civic 2006-2010 1.8 V AT,Mumbai,2007,69000,Petrol,Automatic,Second,12.9 kmpl,1799 CC,130 bhp,5.0,NaN,2.25
3594,3594,Honda Civic 2006-2010 1.8 V MT,Bangalore,2008,66000,Petrol,Manual,Third,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,3.25
3754,3754,Honda Civic 2006-2010 1.8 S MT,Mumbai,2008,87000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,2.35
3835,3835,Honda Civic 2006-2010 1.8 V AT,Kochi,2011,56361,Petrol,Automatic,First,12.9 kmpl,1799 CC,130 bhp,5.0,NaN,4.38
3915,3915,Honda Civic 2010-2013 1.8 V MT,Mumbai,2012,47000,Petrol,Manual,First,14.8 kmpl,1799 CC,130.2 bhp,5.0,NaN,3.95
4593,4593,Honda Civic 2006-2010 1.8 MT Sport,Jaipur,2007,92000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,1.90
4718,4718,Honda Civic 2006-2010 1.8 S MT,Ahmedabad,2009,70000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,4.25
4753,4753,Honda Civic 2010-2013 1.8 V AT Sunroof,Pune,2011,47000,Petrol,Automatic,Second,13.9 kmpl,1799 CC,130.3 bhp,5.0,NaN,4.50
4875,4875,Honda Civic 2006-2010 1.8 S MT,Delhi,2008,80000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,2.75
5343,5343,Honda Civic 2006-2010 1.8 S AT,Pune,2008,152633,Petrol,Automatic,First,12.9 kmpl,1799 CC,130 bhp,5.0,NaN,3.00
5355,5355,Honda Civic 2006-2010 1.8 S MT,Hyderabad,2008,69972,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,3.80
5501,5501,Honda Civic 2006-2010 1.8 V MT,Kolkata,2009,59000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,2.71
5591,5591,Honda Civic 2006-2010 1.8 S MT,Pune,2006,125000,Petrol,Manual,Second,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,2.30
5818,5818,Honda Civic 2006-2010 1.8 V MT,Coimbatore,2009,56927,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,4.41
6043,6043,Honda Civic 2010-2013 1.8 S MT Inspire,Bangalore,2011,40000,Petrol,Manual,Second,15.5 kmpl,1799 CC,132 bhp,5.0,NaN,NaN
6153,6153,Honda Civic 2010-2013 1.8 V AT Sunroof,Pune,2011,61000,Petrol,Automatic,Third,13.9 kmpl,1799 CC,130.3 bhp,5.0,NaN,NaN
6164,6164,Honda Civic 2006-2010 1.8 V MT,Pune,2009,106000,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,NaN
6291,6291,Honda Civic 2006-2010 1.8 V MT,Pune,2010,61696,Petrol,Manual,First,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,NaN
6831,6831,Honda Civic 2010-2013 1.8 V AT,Mumbai,2009,70000,Petrol,Automatic,Third,13.9 kmpl,1799 CC,130.2 bhp,5.0,NaN,NaN
7064,7064,Honda Civic 2006-2010 1.8 (E) MT,Hyderabad,2007,109000,Petrol,Manual,Second,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,NaN
7103,7103,Honda Civic 2006-2010 1.8 MT Sport,Pune,2008,110000,Petrol,Manual,Second,13.5 kmpl,1799 CC,130 bhp,5.0,NaN,NaN

In [5]:
def searchBrand(query):
    query=query.title()
    df=pd.read_csv('/kaggle/input/cars-dataset/used_cars_data.csv')
    filtre=df['Name'].str.contains(query)
    return df[filtre]

In [6]:
searchBrand('vitara')

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
36,36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.12 Lakh,8.63
119,119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.96 Lakh,7.50
201,201,Maruti Vitara Brezza ZDi Plus Dual Tone,Mumbai,2016,20000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.98 Lakh,9.00
343,343,Maruti Vitara Brezza LDi,Chennai,2016,45000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.12 Lakh,7.15
372,372,Maruti Vitara Brezza ZDi Plus,Hyderabad,2017,39000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12 Lakh,9.49
618,618,Maruti Vitara Brezza ZDi,Pune,2016,21558,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,10.65 Lakh,8.90
668,668,Maruti Vitara Brezza ZDi Plus Dual Tone,Coimbatore,2017,18108,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.56 Lakh,11.31
688,688,Maruti Vitara Brezza LDi Option,Pune,2017,38000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,7.99
885,885,Maruti Grand Vitara AT,Chennai,2008,77000,Petrol,Automatic,Fourth & Above,9.7 kmpl,1995 CC,163.5 bhp,5.0,NaN,5.50
1077,1077,Maruti Vitara Brezza ZDi Plus,Kochi,2019,34688,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.2 Lakh,10.49
1094,1094,Maruti Vitara Brezza VDi,Kolkata,2017,35000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.46 Lakh,6.50
1147,1147,Maruti Vitara Brezza ZDi,Coimbatore,2018,64456,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11 Lakh,10.46
1825,1825,Maruti Vitara Brezza VDi Option,Coimbatore,2017,71256,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,9.58
1961,1961,Maruti Vitara Brezza ZDi,Hyderabad,2016,41372,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.02 Lakh,9.30
1995,1995,Maruti Vitara Brezza ZDi Plus AMT Dual Tone,Chennai,2018,3000,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.88 Lakh,11.25
2185,2185,Maruti Vitara Brezza ZDi Plus,Ahmedabad,2017,80000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,10.91 Lakh,8.00
2367,2367,Maruti Grand Vitara 2.4 MT,Kochi,2018,28786,Petrol,Manual,First,10.4 kmpl,2393 CC,163.5 bhp,5.0,NaN,9.74
2384,2384,Maruti Vitara Brezza VDi Option,Delhi,2017,40000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,7.85
2410,2410,Maruti Vitara Brezza ZDi Plus,Jaipur,2017,48324,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.47 Lakh,9.00
2485,2485,Maruti Vitara Brezza ZDi Plus Dual Tone,Kochi,2017,45362,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.75 Lakh,9.38
2534,2534,Maruti Vitara Brezza ZDi,Kolkata,2018,2900,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,10.13 Lakh,8.75
2702,2702,Maruti Vitara Brezza ZDi Plus Dual Tone,Coimbatore,2017,25299,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.56 Lakh,10.34
2707,2707,Maruti Vitara Brezza VDi Option,Kochi,2018,51921,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,8.62
2745,2745,Maruti Vitara Brezza ZDi Plus,Kochi,2017,38426,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.12 Lakh,9.13
3048,3048,Maruti Vitara Brezza VDi Option,Delhi,2017,40000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,7.90
3127,3127,Maruti Vitara Brezza ZDi Plus Dual Tone,Kochi,2017,35981,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.29 Lakh,9.51
3381,3381,Maruti Vitara Brezza LDi,Kochi,2017,35384,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.12 Lakh,8.61
3425,3425,Maruti Vitara Brezza ZDi Plus,Coimbatore,2018,52380,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.47 Lakh,10.15
3726,3726,Maruti Vitara Brezza ZDi Plus Dual Tone,Ahmedabad,2017,33000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.06 Lakh,9.25
3745,3745,Maruti Vitara Brezza ZDi Plus Dual Tone,Coimbatore,2017,26927,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.56 Lakh,11.39
3747,3747,Maruti Vitara Brezza ZDi,Delhi,2016,35299,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,10.14 Lakh,8.00
3838,3838,Maruti Vitara Brezza ZDi Plus Dual Tone,Coimbatore,2018,28741,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.56 Lakh,11.00
4009,4009,Maruti Grand Vitara 2.4 MT,Mumbai,2017,25000,Petrol,Manual,First,10.4 kmpl,2393 CC,163.5 bhp,5.0,NaN,9.00
4301,4301,Maruti Vitara Brezza ZDi Plus Dual Tone,Pune,2016,47300,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.96 Lakh,8.85
4519,4519,Maruti Grand Vitara MT,Mumbai,2008,46810,Petrol,Manual,First,9.8 kmpl,1995 CC,163.5 bhp,5.0,NaN,3.95
4570,4570,Maruti Vitara Brezza ZDi Plus AMT Dual Tone,Chennai,2018,3300,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.88 Lakh,11.50
4590,4590,Maruti Vitara Brezza ZDi,Bangalore,2017,45000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11 Lakh,9.75
4794,4794,Maruti Vitara Brezza VDi Option,Hyderabad,2018,11000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,9.40
4887,4887,Maruti Vitara Brezza ZDi Plus,Kochi,2018,57078,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.58 Lakh,10.19
5019,5019,Maruti Vitara Brezza LDi Option,Pune,2016,31001,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,7.25
5030,5030,Maruti Vitara Brezza LDi,Kochi,2018,32539,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,8.63 Lakh,8.39
5059,5059,Maruti Vitara Brezza ZDi,Coimbatore,2017,58829,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.89 Lakh,9.05
5078,5078,Maruti Vitara Brezza ZDi,Coimbatore,2017,21789,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11 Lakh,9.88
5256,5256,Maruti Vitara Brezza ZDi Plus Dual Tone,Pune,2016,85000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.96 Lakh,8.90
5431,5431,Maruti Vitara Brezza ZDi Plus Dual Tone,Delhi,2016,22000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.75 Lakh,8.25
5872,5872,Maruti Vitara Brezza ZDi Plus Dual Tone,Kochi,2017,21248,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.75 Lakh,9.44
6005,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.93 Lakh,7.43
6075,6075,Maruti Vitara Brezza ZDi,Hyderabad,2016,70687,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.02 Lakh,NaN
6159,6159,Maruti Vitara Brezza VDi Option,Hyderabad,2017,44263,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,NaN
6180,6180,Maruti Vitara Brezza VDi Option,Hyderabad,2017,32248,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,NaN
6370,6370,Maruti Vitara Brezza VDi Option,Delhi,2016,66000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,NaN
6381,6381,Maruti Vitara Brezza LDi,Bangalore,2016,46000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.42 Lakh,NaN
6442,6442,Maruti Vitara Brezza ZDi Plus Dual Tone,Delhi,2017,17660,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.75 Lakh,NaN
6735,6735,Maruti Vitara Brezza ZDi,Pune,2017,35000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,10.65 Lakh,NaN
7119,7119,Maruti Vitara Brezza ZDi,Hyderabad,2016,70746,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.02 Lakh,NaN
7144,7144,Maruti Vitara Brezza ZDi AMT,Coimbatore,2018,57804,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,11.59 Lakh,NaN
7210,7210,Maruti Vitara Brezza VDi Option,Jaipur,2017,19000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN,NaN
7218,7218,Maruti Vitara Brezza ZDi Plus AMT,Mumbai,2018,3800,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.46 Lakh,NaN
7235,7235,Maruti Vitara Brezza ZDi,Kochi,2017,21380,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,10.57 Lakh,NaN

In [7]:
araba_markalari = ["Mercedes", "Land Rover", "Alfa Romeo", "Toyota", "BMW", "Audi", "Honda", "Ford", "Chevrolet", "Volvo", "Volkswagen", "Ferrari", "Lamborghini", "Porsche", "Tesla", "Nissan", "Jeep", "Hyundai", "Kia", "Subaru", "Mazda", "Peugeot", "Renault", "Fiat", "Skoda", "Mitsubishi", "Jaguar", "Cadillac", "Lexus", "Buick", "Chrysler", "Dodge", "GMC", "Infiniti", "Lincoln", "Mini", "Ram", "Acura", "Bentley", "Bugatti", "Genesis", "McLaren", "Maserati", "Rolls-Royce", "Smart", "Suzuki"]

In [8]:
df['Name'].str.split(" ",expand=True)[0].unique()

array(['Maruti', 'Hyundai', 'Honda', 'Audi', 'Nissan', 'Toyota',
       'Volkswagen', 'Tata', 'Land', 'Mitsubishi', 'Renault',
       'Mercedes-Benz', 'BMW', 'Mahindra', 'Ford', 'Porsche', 'Datsun',
       'Jaguar', 'Volvo', 'Chevrolet', 'Skoda', 'Mini', 'Fiat', 'Jeep',
       'Smart', 'Ambassador', 'Isuzu', 'ISUZU', 'Force', 'Bentley',
       'Lamborghini', 'Hindustan', 'OpelCorsa'], dtype=object)

In [9]:
df[df['Name'].str.contains('Land')]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,27.00
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,17.50
191,191,Land Rover Range Rover 2.2L Dynamic,Coimbatore,2018,36091,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,55.76
311,311,Land Rover Range Rover HSE Dynamic,Delhi,2017,44000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,44.00
399,399,Land Rover Range Rover 2.2L Dynamic,Hyderabad,2012,56000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,30.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6434,6434,Land Rover Discovery 4 SDV6 SE,Kochi,2012,89190,Diesel,Automatic,Second,11.4 kmpl,2993 CC,245.41 bhp,7.0,NaN,NaN
6717,6717,Land Rover Discovery Sport TD4 S,Kochi,2018,23342,Diesel,Automatic,First,12.83 kmpl,2179 CC,147.5 bhp,5.0,NaN,NaN
6857,6857,Land Rover Freelander 2 TD4 SE,Mumbai,2011,87000,Diesel,Automatic,First,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,NaN
7157,7157,Land Rover Range Rover 2.2L Pure,Hyderabad,2015,49000,Diesel,Automatic,Second,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,NaN
7198,7198,Land Rover Discovery 4 TDV6 Auto Diesel,Hyderabad,2012,147202,Diesel,Automatic,First,11.8 kmpl,2993 CC,241.6 bhp,7.0,NaN,NaN

In [10]:
df['Name']=df['Name'].str.replace("Land Rover","Land-Rover")

In [11]:
df['Name'].str.split(" ",expand=True)

,0,1,2,3,4,5,6,7,8,9
0,Maruti,Wagon,R,LXI,CNG,None,None,None,None,None
1,Hyundai,Creta,1.6,CRDi,SX,Option,None,None,None,None
2,Honda,Jazz,V,None,None,None,None,None,None,None
3,Maruti,Ertiga,VDI,None,None,None,None,None,None,None
4,Audi,A4,New,2.0,TDI,Multitronic,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen,Vento,Diesel,Trendline,None,None,None,None,None,None
7249,Volkswagen,Polo,GT,TSI,None,None,None,None,None,None
7250,Nissan,Micra,Diesel,XV,None,None,None,None,None,None
7251,Volkswagen,Polo,GT,TSI,None,None,None,None,None,None
7252,Mercedes-Benz,E-Class,2009-2013,E,220,CDI,Avantgarde,None,None,None

In [12]:
df['Brand']=df['Name'].str.split(" ",expand=True)[0]
df['Model']=df['Name'].str.split(" ",expand=True)[1]

In [13]:
df.head(3)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand,Model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,Honda,Jazz

In [14]:
df['Model'].unique()

array(['Wagon', 'Creta', 'Jazz', 'Ertiga', 'A4', 'EON', 'Micra', 'Innova',
       'Vento', 'Indica', 'Ciaz', 'City', 'Swift', 'Range', 'Freelander',
       'Pajero', 'Amaze', 'Duster', 'New', '3', 'S', 'A6', 'i20', 'Alto',
       'WRV', 'Corolla', 'Ssangyong', 'Vitara', 'KUV', 'M-Class', 'Polo',
       'Nano', 'Elantra', 'Xcent', 'Thar', 'Grand', 'KWID', 'i10',
       'X-Trail', 'Zen', 'Figo', 'C-Class', 'Cayenne', 'XUV500',
       'Terrano', 'Brio', 'Fiesta', 'Santro', 'Zest', 'Ritz', '5',
       'Fortuner', 'Ecosport', 'Verna', 'GO', 'Omni', 'Etios', 'XF',
       'Eeco', 'Civic', 'V40', 'B', 'Scorpio', 'CR-V', 'SLC', '1', 'Beat',
       'Rapid', 'RS5', 'Superb', 'X5', 'GLC', 'Countryman', 'Optra',
       'Lodgy', 'E-Class', 'Baleno', 'Laura', 'NuvoSport', 'Fabia',
       'Indigo', 'Q3', 'Octavia', 'A8', 'Verito', 'Cooper', 'Santa', 'X1',
       'Accent', 'Tucson', 'GLE', 'A-Star', 'Grande', 'X3', 'EcoSport',
       'Q7', 'Jetta', 'GLA', 'Celerio', 'Sumo', 'Accord', '6', 'Manza',
       'Spark', 'Clubman', 'Teana', '800', 'BRV', 'XE', 'Xenon', 'A3',
       'GL-Class', 'BR-V', 'S80', 'Captur', 'Enjoy', 'Bolero', 'Q5',
       'Cedia', 'S-Cross', 'Yeti', 'Endeavour', 'GLS', 'A', 'SX4',
       'Camry', 'Mobilio', 'Linea', 'TT', 'Renault', 'Compass', 'Ikon',
       'Sail', 'Quanto', 'Aveo', 'Xylo', 'Esteem', 'Safari', 'Ignis',
       'XJ', 'Sunny', 'SLK-Class', 'Passat', 'Dzire', 'Cruze', 'Koleos',
       'Qualis', 'Ameo', 'redi-GO', 'Fortwo', 'Outlander', 'Cayman',
       'CLA', 'XC60', 'Boxster', 'XUV300', 'Hexa', 'Tiago', '7',
       'Avventura', 'Tigor', 'S60', 'Classic', 'Discovery', 'Beetle',
       'Petra', 'Getz', 'A7', 'Elite', 'Aspire', 'Tiguan', 'Captiva',
       'Punto', 'TUV', 'X6', 'Bolt', 'Evalia', 'Scala', 'Jeep', 'Sonata',
       'Freestyle', 'Logan', 'Tavera', 'Estilo', 'XC90', 'Pulse',
       'Montero', 'Panamera', 'CrossPolo', 'Fluence', 'Venture', 'Nexon',
       'MUX', 'Platinum', 'R-Class', 'CLS-Class', 'D-MAX', 'S-Class',
       'Lancer', 'Redi', 'E', 'Mustang', 'Fusion', 'Siena', '1000',
       'SL-Class', 'Z4', 'Prius', 'One', 'Versa', 'WR-V', 'Continental',
       'Gallardo', 'F', 'Motors', 'Flying', 'Land', 'MU', '370Z',
       'Abarth', '1.4Gsi'], dtype=object)

In [15]:
df.head(3)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand,Model
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,Maruti,Wagon
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,Hyundai,Creta
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,Honda,Jazz

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   object
 2   Location           7253 non-null   object
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   object
 6   Transmission       7253 non-null   object
 7   Owner_Type         7253 non-null   object
 8   Mileage            7251 non-null   object
 9   Engine             7207 non-null   object
 10  Power              7207 non-null   object
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   object
 13  Price              6019 non-null   float64
 14  Brand              7253 non-null   object
 15  Model              7253 non-null   object
dtypes: float64(2), int64(3), object(11)
memory usage: 906.8+ KB

In [17]:
df=df.drop("S.No.",axis=1)

In [18]:
df.head(3)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,Maruti,Wagon
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,Hyundai,Creta
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,Honda,Jazz

In [19]:
df['Engine']=df['Engine'].str.replace("CC","")

In [20]:
#df['Engine'].astype("float64")
df['Engine']=pd.to_numeric(df['Engine'])

In [21]:
df['Power']=df['Power'].str.replace("bhp","")
df['Power']=df['Power'].str.replace("null","0")

In [22]:
df['Power']=df['Power'].astype("float64")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   object
 1   Location           7253 non-null   object
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   object
 5   Transmission       7253 non-null   object
 6   Owner_Type         7253 non-null   object
 7   Mileage            7251 non-null   object
 8   Engine             7207 non-null   float64
 9   Power              7207 non-null   float64
 10  Seats              7200 non-null   float64
 11  New_Price          1006 non-null   object
 12  Price              6019 non-null   float64
 13  Brand              7253 non-null   object
 14  Model              7253 non-null   object
dtypes: float64(4), int64(2), object(9)
memory usage: 850.1+ KB

In [24]:
df['Power']=np.where(df['Power']==0,None,df['Power'])

In [25]:
df.head(3)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998.0,58.16,5.0,NaN,1.75,Maruti,Wagon
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582.0,126.2,5.0,NaN,12.50,Hyundai,Creta
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199.0,88.7,5.0,8.61 Lakh,4.50,Honda,Jazz